Creating tribute page
Hasinarahman/tribute-page pull request #1
Opened 2024-05-22 12:56 UTC by Hasinarahman

Description of tribute page.
 -first Creating a new repo 
-clone the repo in VS code
-creating new html file
-creating css file
-adding linters file
At the html file 
first adding structure of html 
-adding title 
-adding css file link
-in the body tag 
-adding main tag 
-in the main tag 
-adding header tag, h1 and h2 tag, p tag, image tag.
-after main tag adding footer and address tag.
than design the page in css file.
after that push all changes in github.
and creating pull request.

2024-05-22 13:23 UTC, Hasinarahman commented
Hi sir,
I complete the 3 project. please check my project and give me feedback.
@ahzamir

2024-05-22 20:18 UTC, ahzamir requested changes
### Hi @Hasinarahman 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:
- Your HTML code is not aligned correctly and clean **Check the inline comments for more details**
- Copy your HTML file code and paste it to the freecodecamp website survey form project to see which requirements your project is missing solve those missing requirements and mention me here using @ahzamir to re-review your project.

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![SoCloseKeeganMichaelKeyGIF](https://github.com/Hasinarahman/tribute-page/assets/96838030/a154891c-9c1b-4b81-9d10-09ffbbe5fb38)

 ## Highlights 🌞
 
🎯 Great Design implemented.
![Screenshot 2024-05-22 221331](https://github.com/Hasinarahman/tribute-page/assets/96838030/6f446ede-e779-42e2-90d2-85edc2d47d6f)

✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
❌ You have followed and completed the Tribute Page and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
❌ Your code is clean

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-22 20:18 UTC, ahzamir commented on tribute-page.html
- Your HTML code spacing is not aligned correctly:
  - All child elements should be two spaces ahead of their parent element.

**Example:**
```
<div>
  <h1> ... </h1>
  <p>
  .
  .
  </p>
  <div>
    <img ... />
    more elements ...
  </div>
</div>
```

2024-05-23 15:44 UTC, Hasinarahman commented
Hello sir **@ahzamir** ,
I aligned correctly and clean the html code and also paste in freecodecomp it dosen't have problem in it.
and at second time you can check my repo and please tell me your feedback. 
also **thanks** for helping.

2024-05-23 20:40 UTC, ahzamir approved these changes
### Hi @Hasinarahman 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![Screenshot 2024-05-22 221331](https://github.com/Hasinarahman/tribute-page/assets/96838030/6f446ede-e779-42e2-90d2-85edc2d47d6f)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![GreatJobThumbsUpGIF](https://github.com/ZuhRa-HashiMi/survey-form/assets/96838030/cc459d3f-5796-43f0-aba7-4ed0c35fa276)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Odin project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-24 21:26 UTC, merged